version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGO_DB=mongodb+srv://lolemxl:tgqopdc22bQ1acFN@flr-shop.yzxwlqb.mongodb.net/flrshop?retryWrites=true&w=majority&appName=Flr-Shop
    restart: unless-stopped
    networks:
      - eco-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - eco-network

networks:
  eco-network:
    driver: bridge